{% set name = "openfast" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  sha256: 29beab5eba93ab94b411a62eaad38b19b0fba1e04c1fc8e6d79c898d37c6f81e
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

# source:
#   git_url: https://github.com/openfast/openfast.git
#   git_rev: v{{ version }}
#   git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - make
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libblas
    - liblapack

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - rafmudaf
    - openfast
