{% set name = "openfast" %}
{% set version = "3.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # See https://conda-forge.org/docs/maintainer/adding_pkgs/#source
  # conda-forge requests tar-ball urls instead of git actions for source
  # Use `openssl sha256 file.tar.gz` to get sha256 stamp
  url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  sha256: 68714dbf8e82545d2b2e1886c72a97ce2b3127d869724a8ea97db9247e3ec210
  #git_url: https://github.com/openfast/openfast.git
  #git_rev: v{{ version }}
  #git_depth: 1 # (Defaults to -1/not shallow)
  patches:
    - fPIC.patch

build:
  number: 0
  missing_dso_whitelist:
    - "*/libopenfastlib.dll"   # [win]
requirements:
  build:
    - {{ stdlib("c") }}                 # [not win]
    - {{ compiler('c') }}               # [not win]
    - {{ compiler('cxx') }}             # [not win]
    - {{ compiler('fortran') }}         # [not win]
    - {{ compiler('m2w64_c') }}         # [win]
    - {{ compiler('m2w64_cxx') }}       # [win]
    - {{ compiler('m2w64_fortran') }}   # [win]
    - cmake
    - make         # [not win]
    - ninja        # [win]
  host:
    - libgomp      # [not osx]
    - llvm-openmp  # [osx]
    - openblas     # [not win]
    - libblas      # [win]
    - liblapack    # [win]
    #- libcblas
    #- liblapacke    
  run:
    - libgomp      # [not osx]
    - llvm-openmp  # [osx]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h
    - turbsim -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - openfast
    - deslaughter
    - gbarter
    - andrew-platt
