{% set name = "openfast" %}
{% set version = "4.0.2" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    # See https://conda-forge.org/docs/maintainer/adding_pkgs/#source
    # conda-forge requests tar-ball urls instead of git actions for source
    # Use `openssl sha256 file.tar.gz` to get sha256 stamp
    url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
    sha256: 791c1098f7d3df33bb3eeb73043badb6987c9014a91ff7547613673429bd380e
    #git_url: https://github.com/openfast/openfast.git
    #git_rev: v{{ version }}
    #git_depth: 1 # (Defaults to -1/not shallow)
    #patches:
    #  - fPIC.patch

build:
    number: 1
        
outputs:
    - name: openfast
      version: {{ version }}
      script: build.sh                     # [not win]
      script: bld.bat                      # [win]
      build:
          run_exports:
              - {{ pin_subpackage('openfast', max_pin='x.x') }}
          missing_dso_whitelist:
              - "*/libopenfastlib.dll"   # [win]
      requirements:
          build:
              - {{ stdlib("c") }}                 # [not win]
              - {{ compiler('c') }}               # [not win]
              - {{ compiler('cxx') }}             # [not win]
              - {{ compiler('fortran') }}         # [not win]
              - {{ compiler('m2w64_c') }}         # [win]
              - {{ compiler('m2w64_cxx') }}       # [win]
              - {{ compiler('m2w64_fortran') }}   # [win]
              - cmake
              - make         # [not win]
              - ninja        # [win]
          host:
              - libgomp      # [not osx]
              - llvm-openmp  # [osx]
              - openblas     # [not win]
              - libblas      # [win]
              - liblapack    # [win]
              #- libcblas
              #- liblapacke    
          run:
              - libgomp      # [not osx]
              - llvm-openmp  # [osx]

      test:
          commands:
              - openfast -h
              - FAST.Farm -h
              - aerodyn_driver -h
              - hydrodyn_driver -h
              - moordyn_driver -h
              - servodyn_driver -h
              - turbsim -h
              - aerodisk_driver -h
              - sed_driver -h
              - inflowwind_driver -h
              - seastate_driver -h
                
    - name: openfast_io
      version: {{ version }}
      build:
          #string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
          run_exports:
              - {{ pin_subpackage('openfast_io', max_pin='x.x') }}
          skip: True  # [python_impl == 'pypy']
          noarch: python
          script: {{ PYTHON }} -m pip install openfast_io -vv --no-deps --no-build-isolation
          
      requirements:
          host:
              - python {{ python_min }}
              - setuptools >=61
              - hatchling
              - pip
              #- {{ pin_subpackage('openfast', exact=True) }}
          run:
              - python >={{ python_min }}
              - numpy
              - pandas
              - ruamel_yaml
              - deepdiff
              #- {{ pin_subpackage('libmamba', exact=True) }}

      test:
          imports:
              - openfast_io
          requires:
              - python {{ python_min }}

about:
    home: https://github.com/openfast/openfast
    license: Apache-2.0
    license_file: LICENSE
    summary: OpenFAST whole turbine simulation tool
    description: NREL-supported OpenFAST whole-turbine simulation code
    doc_url: http://openfast.readthedocs.io
    dev_url: https://github.com/openfast/openfast

extra:
    feedstock-name: openfast
    recipe-maintainers:
        - deslaughter
        - gbarter
        - andrew-platt
