{% set name = "openfast" %}
{% set version = "dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# source:
#   url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
#   sha256: 2b368e8c8211ebed03e87fb3e89ef733b7e4be4848834da4034f8419d618446c
#   # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

source:
  git_url: https://github.com/openfast/openfast.git
  git_rev: dev
  git_depth: -1 # (Defaults to -1/not shallow)

  
build:
  number: 215
  missing_dso_whitelist:
    - "*/libopenfastlib.dll"   # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - make  # [not win]
    - cmake
    - llvm-openmp  # [osx]
  host:
    - openblas
    - ucrt  # [win]
    - libgomp  # [linux or win]
  run:
    - libopenblas  # [win]
    - ucrt  # [win]
    - libgomp  # [linux or win]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h
    - turbsim -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - openfast
    - deslaughter
    - gbarter
    - andrew-platt
