{% set name = "openfast" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openfast/openfast.git
  git_rev: v{{ version }}
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  skip: True  # [not win]
  number: 3
  missing_dso_whitelist:
    - "*/libopenfastlib.dll"   # [win]
    
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # - {{ compiler('fortran') }}  # [not win]
    # - make  # [not win]
    - cmake
    - ninja  # [win]
    # - llvm-openmp  # [osx]
  host:
    - openblas  # [not win]
    # - libgomp  # [linux or win]
  # run:
    # - libopenblas  # [win]
    # - libgomp  # [linux or win]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h
    - turbsim -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - openfast
    - deslaughter
    - gbarter
    - andrew-platt
