{% set version = "4.1.2" %}

package:
    name: openfast-split
    version: {{ version }}

source:
    # See https://conda-forge.org/docs/maintainer/adding_pkgs/#source
    # conda-forge requests tar-ball urls instead of git actions for source
    # Use `openssl sha256 file.tar.gz` to get sha256 stamp
    url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
    sha256: 940166d4a0d3c1349d8451c7080093f00711c2be38cbf28f2452912b46e52c7a
    #git_url: https://github.com/openfast/openfast.git
    #git_rev: v{{ version }}
    #git_depth: 1 # (Defaults to -1/not shallow)
    patches:
        - ofpy.patch

build:
    number: 1

requirements:
    build:
        - {{ stdlib("c") }}                       # [not win]
        - {{ compiler('c') }}                     # [not win]
        - {{ compiler('cxx') }}                   # [not win]
        - {{ compiler('fortran') }}               # [not win]
        - {{ compiler('m2w64_c') }}               # [win]
        - {{ compiler('m2w64_cxx') }}             # [win]
        - {{ compiler('m2w64_fortran') }}         # [win]
        - cmake
        - make               # [not win]
        - ninja              # [win]
    host:
        - libgomp            # [not osx]
        - llvm-openmp        # [osx]
        - openblas           # [not win]
        - libblas            # [win]
        - liblapack          # [win]
        #- libcblas
        #- liblapacke    
  
outputs:

    - name: openfast
      version: {{ version }}
      script: build_of.sh  # [not win]
      script: bld_of.bat  # [win]
      build:
          #run_exports:
          #    - {{ pin_subpackage('openfast', max_pin='x.x') }}
          missing_dso_whitelist:
              - "*/libopenfastlib.dll"         # [win]
      requirements:
          build:
              - {{ stdlib("c") }}                       # [not win]
              - {{ compiler('c') }}                     # [not win]
              - {{ compiler('cxx') }}                   # [not win]
              - {{ compiler('fortran') }}               # [not win]
              - {{ compiler('m2w64_c') }}               # [win]
              - {{ compiler('m2w64_cxx') }}             # [win]
              - {{ compiler('m2w64_fortran') }}         # [win]
              - cmake
              - make               # [not win]
              - ninja              # [win]
          host:
              - libgomp            # [not osx]
              - llvm-openmp        # [osx]
              - openblas           # [not win]
              - libblas            # [win]
              - liblapack          # [win]
              #- libcblas
              #- liblapacke    
          run:
              - libgomp            # [not osx]
              - llvm-openmp        # [osx]
      test:
          commands:
              #- aerodisk_driver -help
              - aerodyn_driver -h
              #- beamdyn_driver -h
              - FAST.Farm -h
              - hydrodyn_driver -h
              #- inflowwind_driver -help
              - moordyn_driver -h
              - openfast -h
              - seastate_driver -h
              #- sed_driver -help
              - servodyn_driver -h
              #- subdyn_driver -h
              - turbsim -h

            
    - name: openfast-io
      version: {{ version }}
      script: build_io.sh  # [not win]
      script: bld_io.bat  # [win]
      build:
          #noarch: python
          skip: true  # [py<311]
          #script: {{ PYTHON }} -m pip install ./openfast_io -vv --no-deps --no-build-isolation
      requirements:
          build:
              - cross-python_{{ target_platform }}               # [build_platform != target_platform]
              - python                                           # [build_platform != target_platform]
          host:
              - python
              - setuptools
              - hatchling
              - hatch-vcs
              - pip
              #- {{ pin_subpackage('openfast', exact=True) }}
          run:
              - python
              #- {{ pin_compatible('numpy') }}
              - numpy
              - pandas
              - ruamel.yaml
              - deepdiff
              #- {{ pin_subpackage('openfast', exact=True) }}
      test:
          imports:
              - openfast_io
          requires:
              - python

    - name: pyopenfast
      version: {{ version }}
      script: build_pyof.sh  # [not win]
      script: bld_pyof.bat  # [win]
      build:
          #noarch: python
          skip: true  # [py<311]
          #script: {{ PYTHON }} -m pip install ./glue-codes/python -vv --no-deps --no-build-isolation
      requirements:
          build:
              - cross-python_{{ target_platform }}               # [build_platform != target_platform]
              - python                                           # [build_platform != target_platform]
          host:
              - python
              - setuptools
              - pip
              #- {{ pin_subpackage('openfast', exact=True) }}
          run:
              - python
              #- {{ pin_compatible('numpy') }}
              - numpy
              #- {{ pin_subpackage('openfast', exact=True) }}
      test:
          imports:
              - pyOpenFAST
          requires:
              - python

about:
    home: https://github.com/openfast/openfast
    license: Apache-2.0
    license_file: LICENSE
    summary: OpenFAST whole turbine simulation tool
    description: NREL-supported OpenFAST whole-turbine simulation code
    doc_url: http://openfast.readthedocs.io
    dev_url: https://github.com/openfast/openfast

extra:
    feedstock-name: openfast
    recipe-maintainers:
        - deslaughter
        - gbarter
        - andrew-platt
