{% set name = "openfast" %}
{% set version = "3.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  #sha256: 94da085f1d8861a93ab32b6b39335a403d182be0b5f7ff48f63d5805eb7f2b2c
  git_url: https://github.com/openfast/openfast.git
  git_rev: v{{ version }}
  git_depth: 1 # (Defaults to -1/not shallow)
  patches:
      - fPIC.patch
      
build:
  number: 3
  #skip: true  # [not win]

requirements:
  build:
    - {{ stdlib("c") }}                 # [not win]
    - {{ compiler('c') }}               # [not win]
    - {{ compiler('cxx') }}             # [not win]
    - {{ compiler('fortran') }}         # [not win]
    - {{ compiler('m2w64_c') }}         # [win]
    - {{ compiler('m2w64_cxx') }}       # [win]
    - {{ compiler('m2w64_fortran') }}   # [win]
    - make                              # [not win]
    - ninja                             # [win]
    - cmake
    - llvm-openmp                # [osx]
  host:
    - libblas
    - libcblas
    - libgomp                    # [linux]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h
    - turbsim -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - rafmudaf
    - andrew-platt
    - deslaughter
    - gbarter
