{% set name = "openfast" %}
{% set version = "dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# source:
#   url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
#   sha256: 2b368e8c8211ebed03e87fb3e89ef733b7e4be4848834da4034f8419d618446c
#   # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

source:
  git_url: https://github.com/openfast/openfast.git
  git_rev: dev
  git_depth: -1 # (Defaults to -1/not shallow)

  
build:
  number: 311
  missing_dso_whitelist:
    - "*/libopenfastlib.dll"   # [win]

requirements:
  build:
    - {{ stdlib("c") }}                 # [not win]
    - {{ compiler('c') }}               # [not win]
    - {{ compiler('cxx') }}             # [not win]
    - {{ compiler('fortran') }}         # [not win]
    - {{ compiler('m2w64_c') }}         # [win]
    - {{ compiler('m2w64_cxx') }}       # [win]
    - {{ compiler('m2w64_fortran') }}   # [win]
    - cmake
    - make         # [not win]
    - ninja        # [win]
  host:
    - libgomp      # [not osx]
    - llvm-openmp  # [osx]
    - openblas     # [not win]
    - libblas      # [win]
    - liblapack    # [win]
  run:
    - libgomp      # [not osx]
    - llvm-openmp  # [osx]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h
    - turbsim -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - deslaughter
    - gbarter
    - andrew-platt
