{% set name = "openfast" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  sha256: db633a908def86716fd590e3b8761d6ee87bcebd391bb4213476c410d966f1c6
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

# source:
#   git_url: https://github.com/openfast/openfast.git
#   git_rev: v{{ version }}
#   git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make  # [unix]
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libblas  # [unix]
    - liblapack  # [unix]
    - m2w64-openblas  # [win]

test:
  commands:
    - openfast -h     # [unix]
    - FAST.Farm -h     # [unix]
    - aerodyn_driver -h     # [unix]
    - hydrodyn_driver -h     # [unix]
    - moordyn_driver -h     # [unix]
    - servodyn_driver -h     # [unix]
    - openfast.exe /h  # [win]

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - rafmudaf
    - openfast
