conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
choco:
  - mingw --version=13.2.0
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test: native

